[package]
name = "crunch"
version = "0.1.0"
authors = ["sourcepirate <sathyanarrayanan@yandex.com>"]
edition = "2018"


[dependencies]
kmpsearch = "1.0.0"
walkdir = "2.3.1"
docopt = "1.1.0"
serde = "1.0.110"
indicatif = "0.14.0"